console.log("Test")
$(function(){
  $.ajax({
    type:"GET",
    url:"https://pledge-counter.herokuapp.com/api/main/getCount",
    success:function(data){
        $("#pledge-counter").html(data)
    },
    error:function(data){
        console.log(data)
    }
  })
})
